// build-tokens.mjs — converts dist/tokens.js into dist/tokens.css.
// Source of truth: src/tokens/tokens.ts → built by tsup → dist/tokens.js
// Output:           dist/tokens.css ← consumers `@import "@hilum/ui/tokens.css"`
//
// CSS structure (D6, D7):
//   1. Tailwind v4 `@theme` block — palette + brand + fonts + radius + shadow + animations.
//      These become Tailwind utility prefixes (bg-taupe-50, font-serif, shadow-natural, etc.).
//   2. `@theme inline` — semantic mappings that reference the dynamic :root vars.
//   3. `:root` — light-mode defaults for all semantic tokens.
//   4. `@media (prefers-color-scheme: dark)` AND `[data-theme="dark"]` — dark overrides (D7).
//   5. Global keyframes + base typography utilities.

import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const distDir = resolve(__dirname, '..', 'dist')
if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true })

const tokensModule = await import(pathToFileURL(resolve(distDir, 'tokens.js')).href)
const { tokens } = tokensModule

const kebab = (s) => s.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase())

const lines = []
lines.push('/* Hilum UI tokens — generated by scripts/build-tokens.mjs. Do not edit by hand. */')
lines.push('')

/* ---------------- @theme — Tailwind utility palette ---------------- */
lines.push('@theme {')
for (const [k, v] of Object.entries(tokens.taupe))  lines.push(`  --color-taupe-${k}: ${v};`)
for (const [k, v] of Object.entries(tokens.purple)) lines.push(`  --color-purple-${k}: ${v};`)
for (const [k, v] of Object.entries(tokens.brand))  lines.push(`  --color-brand-${k}: ${v};`)
for (const [k, v] of Object.entries(tokens.butter)) lines.push(`  --color-butter-${k}: ${v};`)
lines.push(`  --color-destructive: ${tokens.destructive};`)
lines.push('')
lines.push(`  --font-sans: ${tokens.fontFamily.sans};`)
lines.push(`  --font-serif: ${tokens.fontFamily.serif};`)
lines.push(`  --font-mono: ${tokens.fontFamily.mono};`)
lines.push('')
for (const [k, v] of Object.entries(tokens.radius)) lines.push(`  --radius-${k}: ${v};`)
lines.push('')
lines.push(`  --shadow-natural: ${tokens.shadow.natural};`)
lines.push(`  --shadow-elevated: ${tokens.shadow.elevated};`)
lines.push('')
for (const [k, v] of Object.entries(tokens.animation)) lines.push(`  --animate-${k}: ${v};`)
lines.push('}')
lines.push('')

/* ---------------- @theme inline — semantic var bridge ---------------- */
lines.push('@theme inline {')
for (const k of Object.keys(tokens.semantic.light)) {
  lines.push(`  --color-${kebab(k)}: var(--${kebab(k)});`)
}
lines.push('}')
lines.push('')

/* ---------------- :root — light defaults ---------------- */
lines.push(':root {')
for (const [k, v] of Object.entries(tokens.semantic.light)) {
  lines.push(`  --${kebab(k)}: ${v};`)
}
lines.push('}')
lines.push('')

/* ---------------- dark mode (D7) ---------------- */
const darkBlock = (selector) => {
  lines.push(`${selector} {`)
  for (const [k, v] of Object.entries(tokens.semantic.dark)) {
    lines.push(`  --${kebab(k)}: ${v};`)
  }
  lines.push('}')
  lines.push('')
}
// Auto: prefers-color-scheme.
lines.push('@media (prefers-color-scheme: dark) {')
lines.push('  :root:not([data-theme="light"]) {')
for (const [k, v] of Object.entries(tokens.semantic.dark)) {
  lines.push(`    --${kebab(k)}: ${v};`)
}
lines.push('  }')
lines.push('}')
lines.push('')
// Explicit: data-theme="dark".
darkBlock('[data-theme="dark"]')

/* ---------------- @custom-variant dark ---------------- */
lines.push('@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *, .dark, .dark *));')
lines.push('')

/* ---------------- Type scale utilities ---------------- */
for (const [name, def] of Object.entries(tokens.typeScale)) {
  lines.push(`@utility ${name} {`)
  lines.push(`  font-family: var(--font-${def.family});`)
  lines.push(`  font-size: ${def.size};`)
  lines.push(`  font-weight: ${def.weight};`)
  if (def.lineHeight) lines.push(`  line-height: ${def.lineHeight};`)
  if (def.letterSpacing) lines.push(`  letter-spacing: ${def.letterSpacing};`)
  if (def.textTransform) lines.push(`  text-transform: ${def.textTransform};`)
  lines.push('}')
  lines.push('')
}

/* ---------------- Keyframes ---------------- */
lines.push(`@keyframes accordion-down {
  from { height: 0; }
  to { height: var(--radix-accordion-content-height); }
}
@keyframes accordion-up {
  from { height: var(--radix-accordion-content-height); }
  to { height: 0; }
}
@keyframes caret-blink {
  0%, 70%, 100% { opacity: 1; }
  20%, 50% { opacity: 0; }
}
`)

/* ---------------- Base body / box-sizing ---------------- */
lines.push(`*,
::before,
::after {
  box-sizing: border-box;
  border-color: var(--border);
}

body {
  background-color: var(--background);
  color: var(--foreground);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
`)

const css = lines.join('\n')
writeFileSync(resolve(distDir, 'tokens.css'), css)
console.log(`[build-tokens] dist/tokens.css written (${css.length} bytes)`)
