// build-tokens.mjs — converts dist/tokens.js into dist/tokens.css.
// Source of truth: src/tokens/tokens.ts → built by tsup → dist/tokens.js
// Output:           dist/tokens.css ← consumers `@import "@hilum/ui/tokens.css"`
//
// Consumer setup (globals.css):
//   @import "tailwindcss";
//   @import "@hilum/ui/tokens.css";
//   That's it. The @source directive inside tokens.css handles Tailwind class scanning.
//
// CSS structure (D6, D7):
//   1. @source "../src" — tells Tailwind to scan this package's source for class names.
//   2. Tailwind v4 `@theme` block — palette + brand + fonts + radius + shadow + animations
//      + z-index semantic scale. These become Tailwind utility prefixes (bg-ground-50,
//      font-display, shadow-natural, z-modal, etc.).
//   3. `@theme inline` — semantic mappings that reference the dynamic :root vars.
//   4. `:root` — light-mode defaults for all semantic tokens.
//   5. `@media (prefers-color-scheme: dark)` AND `[data-theme="dark"]` — dark overrides (D7).
//   6. Density tiers (`--density-*` vars) + `compact:` variant for data-density="compact".
//   7. Global keyframes + base typography utilities.

import { writeFileSync, mkdirSync, existsSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { componentCss } from "./component-css.mjs";

const require = createRequire(import.meta.url);

/** Directory of an installed dependency (its package.json may not be exported). */
function packageDir(name) {
  let dir = dirname(require.resolve(name));
  while (!existsSync(resolve(dir, "package.json"))) dir = dirname(dir);
  return dir;
}

function packageVersion(name) {
  return JSON.parse(readFileSync(resolve(packageDir(name), "package.json"), "utf8")).version;
}

/** The CSS string a package passes to its runtime `__insertCSS("…")` call. */
function injectedCss(name) {
  const source = readFileSync(resolve(packageDir(name), "dist", "index.mjs"), "utf8");
  const match = source.match(/__insertCSS\(("(?:[^"\\]|\\.)*")\)/);
  if (!match) throw new Error(`[build-tokens] could not find ${name}'s injected CSS`);
  return JSON.parse(match[1]);
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, "..", "dist");
if (!existsSync(distDir)) mkdirSync(distDir, { recursive: true });

const tokensModule = await import(pathToFileURL(resolve(distDir, "tokens.js")).href);
const { tokens } = tokensModule;

const kebab = (s) => s.replace(/[A-Z]/g, (m) => "-" + m.toLowerCase());

const lines = [];
lines.push("/* Hilum UI tokens — generated by scripts/build-tokens.mjs. Do not edit by hand. */");
lines.push("");
// Tell Tailwind where to scan for @hilum/ui class names. Resolved relative to
// this file's location (dist/tokens.css → ../src = node_modules/@hilum/ui/src),
// so consumers never need their own @source pointing into node_modules.
lines.push('@source "../src";');
lines.push("");

/* ---------------- @theme — Tailwind utility palette ---------------- */
lines.push("@theme {");
for (const [k, v] of Object.entries(tokens.ground)) lines.push(`  --color-ground-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.purple)) lines.push(`  --color-purple-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.brand)) lines.push(`  --color-brand-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.butter)) lines.push(`  --color-butter-${k}: ${v};`);
lines.push(`  --color-destructive: ${tokens.destructive};`);
lines.push("");
lines.push(`  --font-sans: ${tokens.fontFamily.sans};`);
lines.push(`  --font-display: ${tokens.fontFamily.display};`);
lines.push(`  --font-mono: ${tokens.fontFamily.mono};`);
lines.push("");
for (const [k, v] of Object.entries(tokens.radius)) lines.push(`  --radius-${k}: ${v};`);
lines.push("");
lines.push(`  --shadow-natural: ${tokens.shadow.natural};`);
lines.push(`  --shadow-elevated: ${tokens.shadow.elevated};`);
lines.push("");
for (const [k, v] of Object.entries(tokens.animation)) lines.push(`  --animate-${k}: ${v};`);
lines.push("");
for (const [k, v] of Object.entries(tokens.zIndex)) lines.push(`  --z-${k}: ${v};`);
lines.push("}");
lines.push("");

/* ---------------- @theme inline — semantic var bridge ---------------- */
lines.push("@theme inline {");
for (const k of Object.keys(tokens.semantic.light)) {
  lines.push(`  --color-${kebab(k)}: var(--${kebab(k)});`);
}
// Surface elevation ladder → bg-surface-N / shadow-surface-N utilities
// (emitted by lib/surface-classes.ts). Values are per-theme :root vars below.
const surfaceLevels = tokens.surfaces.light.bg.map((_, i) => i + 1);
for (const n of surfaceLevels) lines.push(`  --color-surface-${n}: var(--surface-${n});`);
for (const n of surfaceLevels) lines.push(`  --shadow-surface-${n}: var(--surface-shadow-${n});`);
// Categorical hues → bg-categorical-red / text-categorical-blue / …
for (const k of Object.keys(tokens.categorical ?? {})) {
  lines.push(`  --color-categorical-${k}: var(--categorical-${k});`);
}
lines.push("}");
lines.push("");

// All per-theme custom properties: semantic colours + the surface ladder.
const themeVars = (theme) => {
  const vars = Object.entries(tokens.semantic[theme]).map(([k, v]) => [`--${kebab(k)}`, v]);
  const surfaces = tokens.surfaces[theme];
  if (surfaces) {
    surfaces.bg.forEach((v, i) => vars.push([`--surface-${i + 1}`, v]));
    surfaces.shadow.forEach((v, i) => vars.push([`--surface-shadow-${i + 1}`, v]));
  }
  return vars;
};
const themeBlock = (selector, theme, indent = "") => {
  lines.push(`${indent}${selector} {`);
  for (const [k, v] of themeVars(theme)) lines.push(`${indent}  ${k}: ${v};`);
  lines.push(`${indent}}`);
};

/* ---------------- :root — light defaults ---------------- */
themeBlock(":root", "light");
lines.push("");

/* ---------------- :root — categorical hues (theme-independent) ---------------- */
if (tokens.categorical) {
  lines.push(":root {");
  for (const [k, v] of Object.entries(tokens.categorical))
    lines.push(`  --categorical-${k}: ${v};`);
  lines.push("}");
  lines.push("");
}

/* ---------------- dark mode (D7) ---------------- */
// Auto: prefers-color-scheme.
lines.push("@media (prefers-color-scheme: dark) {");
themeBlock(':root:not([data-theme="light"])', "dark", "  ");
lines.push("}");
lines.push("");
// Explicit: data-theme="dark".
themeBlock('[data-theme="dark"]', "dark");
lines.push("");

// Mid theme — explicit opt-in only (no prefers-color-scheme auto).
if (tokens.semantic.mid) {
  themeBlock('[data-theme="mid"]', "mid");
  lines.push("");
}

/* ---------------- density tiers ---------------- */
// Default tier on :root; compact tier on any [data-density="compact"] subtree.
const densityBlock = (selector, tier) => {
  lines.push(`${selector} {`);
  for (const [k, v] of Object.entries(tokens.density[tier]))
    lines.push(`  --density-${kebab(k)}: ${v};`);
  lines.push("}");
};
densityBlock(":root", "default");
densityBlock('[data-density="compact"]', "compact");
lines.push("");
// `compact:` variant — components opt their compact sizing in with e.g.
// `compact:h-6`. Matches the element carrying the attribute and descendants.
lines.push(
  '@custom-variant compact (&:where([data-density="compact"], [data-density="compact"] *));',
);
lines.push("");

/* ---------------- @custom-variant dark ---------------- */
lines.push(
  '@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *, .dark, .dark *));',
);
lines.push("");

/* ---------------- Type scale utilities ---------------- */
for (const [name, def] of Object.entries(tokens.typeScale)) {
  lines.push(`@utility ${name} {`);
  lines.push(`  font-family: var(--font-${def.family});`);
  lines.push(`  font-size: ${def.size};`);
  lines.push(`  font-weight: ${def.weight};`);
  if (def.lineHeight) lines.push(`  line-height: ${def.lineHeight};`);
  if (def.letterSpacing) lines.push(`  letter-spacing: ${def.letterSpacing};`);
  if (def.textTransform) lines.push(`  text-transform: ${def.textTransform};`);
  if (def.textWrap) lines.push(`  text-wrap: ${def.textWrap};`);
  lines.push("}");
  lines.push("");
}

/* ---------------- Keyframes ---------------- */
lines.push(`@keyframes accordion-down {
  from { height: 0; }
  to { height: var(--radix-accordion-content-height); }
}
@keyframes accordion-up {
  from { height: var(--radix-accordion-content-height); }
  to { height: 0; }
}
@keyframes caret-blink {
  0%, 70%, 100% { opacity: 1; }
  20%, 50% { opacity: 0; }
}
@keyframes hilum-orbit {
  0% { stroke-dasharray: 10 90; stroke-dashoffset: 0; }
  50% { stroke-dasharray: 28 72; stroke-dashoffset: -18; }
  100% { stroke-dasharray: 10 90; stroke-dashoffset: -100; }
}
@keyframes hilum-spring-in {
  0% { opacity: 0; transform: scale(0.92); }
  70% { opacity: 1; transform: scale(1.04); }
  100% { opacity: 1; transform: scale(1); }
}
@keyframes hilum-thinking {
  0%, 100% { opacity: 0.42; transform: translateY(0) scale(0.92); }
  50% { opacity: 1; transform: translateY(-1px) scale(1); }
}
`);

/* ---------------- Base body / box-sizing / editor chrome ---------------- */
// Inside @layer base so border-{color} / bg utilities (layer utilities) win;
// unlayered, this rule silently overrode every border colour utility.
// Compact (editor-chrome) subtrees get plain tabular Inter digits (the
// app-wide ss01/ss02 read as code in inspectors) and a finer 1.5px lucide
// stroke; base layer on purpose, so group-hover:[&_svg]:stroke-[2] still wins.
lines.push(`@layer base {
  *,
  ::before,
  ::after {
    box-sizing: border-box;
    border-color: var(--border);
  }

  html,
  body {
    background-color: var(--background);
    color: var(--foreground);
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  [data-density="compact"] {
    font-feature-settings: "tnum" 1, "cv11" 1;
  }

  [data-density="compact"] svg.lucide {
    stroke-width: 1.5px;
  }
}
`);

/* ---------------- Component CSS (CSP-safe, see scripts/component-css.mjs) ---------------- */
lines.push(componentCss);
lines.push("");

/* ---------------- sonner + vaul CSS, statically ---------------- */
// sonner (toasts) and vaul (drawers) insert their CSS with a runtime <style>
// when imported. @hilum/ui bundles both with that injection stripped
// (scripts/strip-injected-css.mjs), so the exact CSS they would inject ships
// here: no CSP violation, and every app that imports tokens.css gets it.
lines.push(`/* ---- sonner ${packageVersion("sonner")} (toasts), was injected at runtime ---- */`);
lines.push(injectedCss("sonner"));
lines.push("");
lines.push(`/* ---- vaul ${packageVersion("vaul")} (drawers), was injected at runtime ---- */`);
// vaul ships one invalid rule (`[data-vaul-handle-hitarea]:{…}`) that browsers
// drop anyway; strip it so CSS minifiers in consumer builds don't choke.
lines.push(
  injectedCss("vaul").replace(
    /@media \(pointer:fine\)\{\[data-vaul-handle-hitarea\]:\{[^}]*\}\}/,
    "",
  ),
);
lines.push("");

const css = lines.join("\n");
writeFileSync(resolve(distDir, "tokens.css"), css);
console.log(`[build-tokens] dist/tokens.css written (${css.length} bytes)`);

/* ---------------- vendor.css — kept for existing imports ---------------- */
// 4.2 shipped the sonner + vaul CSS here for strict-CSP apps. Since 4.4 it is
// part of tokens.css; this file stays (empty) so existing
// `@import "@hilum/ui/vendor.css"` lines keep resolving without duplicating it.
const vendorCss = [
  "/* Hilum UI vendor CSS — generated by scripts/build-tokens.mjs. Do not edit by hand.",
  " * Deprecated: since @hilum/ui 4.4 the sonner and vaul CSS ships in tokens.css,",
  " * and neither library injects a <style> any more. Remove this import.",
  " */",
  "",
].join("\n");
writeFileSync(resolve(distDir, "vendor.css"), vendorCss);
console.log(`[build-tokens] dist/vendor.css written (${vendorCss.length} bytes)`);
