// build-fonts.mjs — copies Inter + Gabarito .woff2 files from
// @fontsource into dist/fonts/, and writes dist/fonts.css with @font-face
// rules using the canonical family names ('Inter', 'Gabarito') that
// match the tokens in src/tokens/tokens.ts.
//
// Consumer setup (globals.css):
//   @import "@hilum/ui/tokens.css";
//   @import "@hilum/ui/fonts.css";   // opt-in, self-hosted fonts
//
// Why self-hosted: no Google Fonts dependency (offline-safe, no privacy
// concerns), no DNS lookup at runtime, bundler can fingerprint + cache.

import { mkdirSync, copyFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { createRequire } from 'node:module'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const distDir = resolve(pkgRoot, 'dist')
const fontsDir = resolve(distDir, 'fonts')

mkdirSync(fontsDir, { recursive: true })

// Resolve files from @fontsource packages.
const require = createRequire(pathToFileURL(resolve(pkgRoot, 'package.json')).href)

function fontsourceFile(pkg, file) {
  return require.resolve(`${pkg}/files/${file}`)
}

// Subsets we ship: latin + latin-ext (covers English, all of Western/Central
// Europe, Vietnamese, etc.). Cyrillic / Greek / Vietnamese-only subsets are
// skipped to keep the package small — apps that need them can layer their own
// @font-face on top.
const GABARITO_WEIGHTS = [400, 500, 600, 700, 800, 900]

const COPIES = [
  // Inter variable (single file covers weights 100-900)
  ['@fontsource-variable/inter', 'inter-latin-wght-normal.woff2'],
  ['@fontsource-variable/inter', 'inter-latin-wght-italic.woff2'],
  ['@fontsource-variable/inter', 'inter-latin-ext-wght-normal.woff2'],
  ['@fontsource-variable/inter', 'inter-latin-ext-wght-italic.woff2'],
  // Gabarito (static normal weights 400-900)
  ...GABARITO_WEIGHTS.flatMap((weight) => [
    ['@fontsource/gabarito', `gabarito-latin-${weight}-normal.woff2`],
    ['@fontsource/gabarito', `gabarito-latin-ext-${weight}-normal.woff2`],
  ]),
]

for (const [pkg, file] of COPIES) {
  const src = fontsourceFile(pkg, file)
  if (!existsSync(src)) {
    throw new Error(`[build-fonts] missing source: ${src}`)
  }
  copyFileSync(src, resolve(fontsDir, file))
}

// Unicode ranges copied from @fontsource (kept inline so consumers don't need
// the @fontsource packages at runtime).
const UNICODE = {
  'latin':
    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,' +
    'U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,' +
    'U+2212,U+2215,U+FEFF,U+FFFD',
  'latin-ext':
    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,' +
    'U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,' +
    'U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
}

function interFace({ subset, style }) {
  return `@font-face {
  font-family: 'Inter';
  font-style: ${style};
  font-display: swap;
  font-weight: 100 900;
  src: url('./fonts/inter-${subset}-wght-${style}.woff2') format('woff2-variations');
  unicode-range: ${UNICODE[subset]};
}`
}

function gabaritoFace({ subset, weight }) {
  return `@font-face {
  font-family: 'Gabarito';
  font-style: normal;
  font-display: swap;
  font-weight: ${weight};
  src: url('./fonts/gabarito-${subset}-${weight}-normal.woff2') format('woff2');
  unicode-range: ${UNICODE[subset]};
}`
}

const css = [
  '/* Hilum UI fonts — generated by scripts/build-fonts.mjs. Do not edit by hand. */',
  '/* Inter (variable, 100-900) + Gabarito (400-900), latin + latin-ext subsets. */',
  '',
  interFace({ subset: 'latin', style: 'normal' }),
  '',
  interFace({ subset: 'latin', style: 'italic' }),
  '',
  interFace({ subset: 'latin-ext', style: 'normal' }),
  '',
  interFace({ subset: 'latin-ext', style: 'italic' }),
  '',
  ...GABARITO_WEIGHTS.flatMap((weight) => [
    gabaritoFace({ subset: 'latin', weight }),
    '',
    gabaritoFace({ subset: 'latin-ext', weight }),
    '',
  ]),
  '',
].join('\n')

writeFileSync(resolve(distDir, 'fonts.css'), css)
console.log(`[build-fonts] wrote dist/fonts.css (${css.length} bytes) + ${COPIES.length} woff2 files`)
